### ISSUE TITLE
Outdated Code of Conduct

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-fish-tools/Resources#5]
Thank you for providing a Code of Conduct file that we have been linking to in other repositories. The newest version is 2.1. I propose creating a GitHub action that would notify FIT if a newer version is available. Also, I would like to provide more information on why open source projects suggest having a Code of Conduct. I can write the action and the documentation but I wanted to check with @ChristineStawitz-NOAA and others if the proposal is a good idea.

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA I know this is an old post, but I'm still thinking about it! I noticed that you can follow https://github.com/EthicalSource/contributor_covenant to see when new releases come out (for me, I set it to only notify for releases and not other activity); maybe that will work instead of having to make a github action?

If you still want to add additional documentation, that would be great! Note there is also documentation on Code of conducts here: https://nmfs-opensci.github.io/ResourceBook/content/code_of_conduct.html . 

Would you like me to replace the current code of conduct with version 2.1 (after reading through and making sure it works for us)

**Comment by kellijohnson-NOAA** [comment]
I read through the changes made for version 2.1 ([commit b49434e6](https://github.com/EthicalSource/contributor_covenant/commit/b49434e6ee1467481b1d68641e5bc7eb78f73714)) and most changes were to Contributing.md and are pretty benign. The one change to the Code of Conduct is the email address for reporting, which is now `conduct at ethicalsource dot dev`.

**Comment by kellijohnson-NOAA** [comment]
Oops those were the changes from 2.0 to 2.1. We are back on 1.4. I will look and see the differences between 1.4 to 2.1. Sorry.

**Comment by kellijohnson-NOAA** [comment]
1.4 to 2.0 includes major changes, hence the change in the "major" number 😆 . Changes from 2.0 to 2.1 are small and great.

The major changes from 1.4 to 2.0 include the addition of "Enforcement Guidelines". I do not feel comfortable deciding if they align with our community. They are fairly specific and should be approved by the community at large.

I think that it would be easy to create a GitHub action to at least open an issue that there is a new version. And, it would not be that much more to modify to to make a pull request. Up to you.

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA and @ChristineStawitz-NOAA were just talking about code of conduct enforcement yesterday. I just read through version 2.1 (https://www.contributor-covenant.org/version/2/1/code_of_conduct/) and really like the inclusion of the enforcement guidelines, personally. But I agree, Kelli, that it takes more than one person to decide that they are right for our community, and so would like other's input!
